version: '3.4'

services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - ./src:/code/src:ro
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=user
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DATABASE=user
    depends_on:
      - redis
      - mongo

  redis:
    image: 'redis:4.0-alpine'
    logging:
      driver: 'none'

  mongo:
    image: 'mongo:4.0'
    logging:
      driver: 'none'

  postgres:
    image: 'postgres:11'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
